# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json

language: en-US

reviews:
  high_level_summary: true
  poem: false
  review_status: true

  # Project context for reviewers
  path_instructions:
    - path: "src/**"
      instructions: |
        Dream Auth is a self-hosted identity provider built on TanStack Start with BetterAuth.
        Key directories:
        - src/lib/auth.ts: Central authentication configuration
        - src/lib/oidc/: OIDC provider implementation
        - src/routes/: TanStack Start file-based routing
        - src/components/: React components (shadcn/ui in ui/)
        - src/env.ts: Server-only env vars (never import in client code)
        - src/env.client.ts: Client-safe env vars (VITE_* prefixed)
    - path: "server/**"
      instructions: |
        Nitro server plugins. The auto-migrate plugin handles BetterAuth database migrations
        with PostgreSQL advisory locks for safe multi-replica deployments.
    - path: "**/*.test.ts"
      instructions: |
        Tests use Vitest. Mock factories live in test/mocks/.
        Prefer typed mock factories over type casting.

  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main

  tools:
    biome:
      enabled: true
    eslint:
      enabled: false

chat:
  auto_reply: true
